---
# Task file : OpenStack VM creation

# Creating OpenStack server

- name: Creating VM in OpenStack
  os_server:
    validate_certs: False
    api_timeout: 300
    timeout: 600
    state: "{{ vm_state }}"
    auth:
      auth_url: "{{ cloudstack_auth_url }}"
      username: "{{ cloudstack_login }}"
      password: "{{ cloudstack_password }}"
      project_name: "{{ cloudstack_project }}"
    auth_type: v2password
    auto_ip: false
    region_name: "{{ vm_region_name }}"
    availability_zone: "{{ vm_availability_zone }}"
    key_name: "{{ vm_key_name }}"
    flavor: "{{ vm_flavor }}"
    image: "{{ vm_image }}"
    meta:
      description: "{{ vm_description }}"
    name: "{{ vm_hostname }}"
    security_groups: "{{ vm_security_group }}"
    #network: "{{ vm_network }}"
    userdata: "{{ lookup('file', '{{ inventory_dir }}/user_data_vm/user_data.sh') }}"
    nics: "{{ vm_networks }}"
  register: my_server

- debug:
        var: my_server.server.accessIPv4
        
# Waiting for server to boot
- name: Waiting for VM to boot using public access
  sudo: no
  when: my_server|changed and vm_public_access
  local_action: wait_for host="{{ my_server.server.public_v4 }}" port=22 timeout=300 search_regex=OpenSSH delay=5

- name: Waiting for VM to boot using private access
  sudo: no
  when: my_server|changed and vm_public_access == false
  local_action: wait_for host="{{ my_server.server.private_v4 }}" port=22 timeout=300 search_regex=OpenSSH delay=5
